sudo: true
language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - build-essential
    - libtool 
    - autotools-dev
    - automake
    - pkg-config
    - bsdmainutils
    - python3
    - libssl-dev
    - libevent-dev
    - libboost-all-dev
    - zlib1g-dev
    - libseccomp-dev
    - libcap-dev
    - libncap-dev
    - libdb-dev
    - libdb++-dev
    - libminiupnpc-dev
    - libzmq3-dev
    - libqt5gui5
    - libqt5core5a
    - libqt5dbus5
    - qttools5-dev
    - qttools5-dev-tools
    - libprotobuf-dev
    - protobuf-compiler
    - libqrencode-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  # openssl and boost are already pre-installed on travis
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install automake berkeley-db4 libtool miniupnpc pkg-config protobuf python qt libevent qrencode; fi

script:
  - ./autogen.sh # prepare all build-aux and update submodules
  - ./configure --with-incompatible-bdb --disable-bench # configure all sources for the compiling process
  - make -j3 # make sources 