name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 12 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: | 
          Your issue hasn't been processed. I'm pushing your issue again, either someone will follow up or close it.
        stale-pr-message: |
          'Your pull request hasn't been touched for a long time, please check if there's something left to do. Thank you.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
